#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "parser.h"
#include "lexer.h"

int line;
int column;
char last,ch;
FILE * fp;
extern entry lookup_table[40];
extern entry_map_nt map_nt[56];
extern entry_map_t map_t[59];
int parseTable[56][59];
table T;
int main(int argc, char* argv[])
{
	if( argc == 3 ) 
	{
		init();
		init_map_t();
		init_map_nt();

		grammar g = get_grammar();

		FirstAndFollow f = ComputeFirstAndFollowSets(g);
		
		fill_parseTable(g,f,T.parseTable);
		parseTree programNode=*((parseTree* )malloc(sizeof(parseTree)));
		
		fp=fopen( "clean_code.txt", "r" );
		line=0;
		column=1;
		printf("-----FIRST AND FOLLOW AUTOMATED-----\n");
		int num=-1;
		
		while(1)
		{
			if(num==1){ 
				removeComments(argv[1],"clean_code.txt"); 
				FILE* clean_fp=fopen("clean_code.txt","r");
				char c;
				while((c=fgetc(clean_fp))!=EOF)
	       			printf("%c",c);
				num=-1; 
			}
			else if(num==2)
			{
				LexerOutput(argv[1]);
				fp=fopen( "clean_code.txt", "r" );
				line=0;
				column=1;
				num=-1;
			}
			else if (num==3)
			{
				programNode=parseInputSourceCode(argv[1],T,g,f);
				// fclose(fp);
				fp=fopen( "clean_code.txt", "r" );
				line=0;
				column=1;
				num=-1;
			}  
			else if(num==4)
			{
				FILE* out_fp=fopen(argv[2],"w");
				programNode=parseInputSourceCode(argv[1],T,g,f);
				parseTreePrint(&programNode.begin,out_fp);
				fp=fopen( "clean_code.txt", "r" );
				num=-1;
				line=0;
				column=1;
			}  
			else if(num==-1){
				printf("\nPress:\n1=> For the clean code\n");
				printf("2=> For printing token generated by lexer\n");
				printf("3=> For verifying the syntactic correctness\n");
				printf("4=> For printing the parse tree\n");
				printf("5=> For Exiting\n");
				scanf(" %d",&num);
				if(num==-1)
					num=0;
			}
			else if(num==5)
				break;
			else{
				printf("Incorrect Input.\n");
				num=-1;
				break;
			}
		}
	}
	else if( argc > 3 ) {
	    printf("Too many arguments supplied.\n");
	}
	else{
	    printf("Insufficient arguments.\n");
	}
	return 0;
}