#include "index_nt.h"
#include <stdio.h>
#include <string.h>
entry_map_nt map_nt[57];
int get_index_nt(char * a)
{
	for(int i=0;i<57;i++)
	{
		if(!strcmp(map_nt[i].incoming,a)){

			return map_nt[i].index;
		}
	}
	return -1;
}
void init_map_nt()
{
	sprintf(map_nt[0].incoming,"INTEGER");
	map_nt[0].index=0;
	sprintf(map_nt[1].incoming,"REAL");
	map_nt[1].index=1;
	sprintf(map_nt[2].incoming,"BOOLEAN");
	map_nt[2].index=2;
	sprintf(map_nt[3].incoming,"OF");
	map_nt[3].index=3;
	sprintf(map_nt[4].incoming,"ARRAY");
	map_nt[4].index=4;
	sprintf(map_nt[5].incoming,"START");
	map_nt[5].index=5;
	sprintf(map_nt[6].incoming,"END");
	map_nt[6].index=6;
	sprintf(map_nt[7].incoming,"DECLARE");
	map_nt[7].index=7;
	sprintf(map_nt[8].incoming,"MODULE");
	map_nt[8].index=8;
	sprintf(map_nt[9].incoming,"DRIVER");
	map_nt[9].index=9;
	sprintf(map_nt[10].incoming,"PROGRAM");
	map_nt[10].index=10;
	sprintf(map_nt[11].incoming,"GET_VALUE");
	map_nt[11].index=11;
	sprintf(map_nt[12].incoming,"PRINT");
	map_nt[12].index=12;
	sprintf(map_nt[13].incoming,"USE");
	map_nt[13].index=13;
	sprintf(map_nt[14].incoming,"WITH");
	map_nt[14].index=14;
	sprintf(map_nt[15].incoming,"PARAMETERS");
	map_nt[15].index=15;
	sprintf(map_nt[16].incoming,"TRUE");
	map_nt[16].index=16;
	sprintf(map_nt[17].incoming,"FALSE");
	map_nt[17].index=17;
	sprintf(map_nt[18].incoming,"TAKES");
	map_nt[18].index=18;
	sprintf(map_nt[19].incoming,"INPUT");
	map_nt[19].index=19;
	sprintf(map_nt[20].incoming,"RETURNS");
	map_nt[20].index=20;
	sprintf(map_nt[21].incoming,"AND");
	map_nt[21].index=21;
	sprintf(map_nt[22].incoming,"OR");
	map_nt[22].index=22;
	sprintf(map_nt[23].incoming,"FOR");
	map_nt[23].index=23;
	sprintf(map_nt[24].incoming,"IN");
	map_nt[24].index=24;
	sprintf(map_nt[25].incoming,"SWITCH");
	map_nt[25].index=25;
	sprintf(map_nt[26].incoming,"CASE");
	map_nt[26].index=26;
	sprintf(map_nt[27].incoming,"BREAK");
	map_nt[27].index=27;
	sprintf(map_nt[28].incoming,"DEFAULT");
	map_nt[28].index=28;
	sprintf(map_nt[29].incoming,"WHILE");
	map_nt[29].index=29;
	sprintf(map_nt[30].incoming,"PLUS");
	map_nt[30].index=30;
	sprintf(map_nt[31].incoming,"MINUS");
	map_nt[31].index=31;
	sprintf(map_nt[32].incoming,"MUL");
	map_nt[32].index=32;
	sprintf(map_nt[33].incoming,"DIV");
	map_nt[33].index=33;
	sprintf(map_nt[34].incoming,"LT");
	map_nt[34].index=34;
	sprintf(map_nt[35].incoming,"LE");
	map_nt[35].index=35;
	sprintf(map_nt[36].incoming,"GE");
	map_nt[36].index=36;
	sprintf(map_nt[37].incoming,"GT");
	map_nt[37].index=37;
	sprintf(map_nt[38].incoming,"EQ");
	map_nt[38].index=38;
	sprintf(map_nt[39].incoming,"NE");
	map_nt[39].index=39;
	sprintf(map_nt[40].incoming,"DEF");
	map_nt[40].index=40;
	sprintf(map_nt[41].incoming,"ENDDEF");
	map_nt[41].index=41;
	sprintf(map_nt[42].incoming,"COLON");
	map_nt[42].index=42;
	sprintf(map_nt[43].incoming,"RANGEOP");
	map_nt[43].index=43;
	sprintf(map_nt[44].incoming,"SEMICOL");
	map_nt[44].index=44;
	sprintf(map_nt[45].incoming,"COMMA");
	map_nt[45].index=45;
	sprintf(map_nt[46].incoming,"ASSIGNOP");
	map_nt[46].index=46;
	sprintf(map_nt[47].incoming,"SQBO");
	map_nt[47].index=47;
	sprintf(map_nt[48].incoming,"SQBC");
	map_nt[48].index=48;
	sprintf(map_nt[49].incoming,"BO");
	map_nt[49].index=49;
	sprintf(map_nt[50].incoming,"BC");
	map_nt[50].index=50;
	sprintf(map_nt[51].incoming,"COMMENTMARK");
	map_nt[51].index=51;
	sprintf(map_nt[52].incoming,"RNUM");
	map_nt[52].index=52;
	sprintf(map_nt[53].incoming,"NUM");
	map_nt[53].index=53;
	sprintf(map_nt[54].incoming,"ID");
	map_nt[54].index=54;
	sprintf(map_nt[55].incoming,"DRIVERDEF");
	map_nt[55].index=55;
	sprintf(map_nt[56].incoming,"DRIVERENDDEF");
	map_nt[56].index=56;
	
}
